### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by besuperhuman** [2beDigital/solidus_bootstraps_frontend#2]
<img width="1295" alt="screen shot 2017-05-22 at 6 28 51 pm" src="https://cloud.githubusercontent.com/assets/28880670/26334808/89df9300-3f1c-11e7-8c24-ca61369144bf.png">
 Would love help!!

**Comment by NoelDiazMesa** [comment]
Yes, there is a bug... Can you update?? Thanks a lot for report this
