### ISSUE TITLE
Another Error

### ISSUE THREAD

**Issue by VladVelev** [2beDigital/solidus_bootstraps_frontend#3]
Hello guys, 

So I have a really fresh Solidus installation, which I use a lot. I gave a try to your gem, but the following error appears: 

```
NameError in Spree::Home#index
Showing /home/dread/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-a96bf20abc21/solidus_bootstrap/frontend/app/views/spree/shared/_locale_selector.html.erb where line #1 raised:

```
Please check the attachment and advise. Cheers! 
![solidus-gem](https://user-images.githubusercontent.com/22999936/33947205-75ffae90-e02c-11e7-8d97-33f9ea0720d9.PNG)

**Comment by aaronsmulktis** [comment]
same here... I tried tons of smart stuff to fix, but didn't work

**Comment by NoelDiazMesa** [comment]
Yes, you need instal Solidus_globalize, if not using solidus_globalize you need to update this gem. 

Thanks a lot!
